<?php 
/************************************************************************/
/* AChecker                                                             */
/************************************************************************/
/* Copyright (c) 2008 by Greg Gay, Cindy Li                             */
/* Adaptive Technology Resource Centre / University of Toronto          */
/*                                                                      */
/* This program is free software. You can redistribute it and/or        */
/* modify it under the terms of the GNU General Public License          */
/* as published by the Free Software Foundation.                        */
/************************************************************************/
/* This file was generated by the AChecker 1.0 installation script.     */
/* File generated 2010-06-04 15:06:32                                   */
/************************************************************************/
/************************************************************************/
/* the database user name                                               */
define('DB_USER',                      'root');

/* the database password                                                */
define('DB_PASSWORD',                  '');

/* the database host                                                    */
define('DB_HOST',                      'localhost');

/* the database tcp/ip port                                             */
define('DB_PORT',                      '3306');

/* the database name                                                    */
define('DB_NAME',                      'achecker');

/* The prefix to add to table names to avoid conflicts with existing    */
/* tables. Default: AC_                                                 */
define('TABLE_PREFIX',                 'AC_');

/* Where the temporary files are located.  This includes all file       */
/* manager and imported files.  If security is a concern, it is         */
/* recommended that the temporary directory be moved outside of the web	*/
/* accessible area.														*/
define('AC_TEMP_DIR', 'E:\\temp\\');

/* DO NOT ALTER THIS LAST LINE                                          */
define('AC_INSTALL', TRUE);

?>